Repository ia-cloud/node-red-contrib-ia-cloud-fds, pull requests merged in 2020-10, with the labels that each got.

#43 Fix display problem of node label. #41
  urd/locales/en-US/urd-obj.json
  urd/locales/ja/urd-obj.json
  urd/urd-obj.html
Labels: bug

#44 Use EnOcean-com instead of urd-com. #42
  package.json
  urd/locales/en-US/urd-com.json
  urd/locales/en-US/urd-obj.json
  urd/locales/ja/urd-com.html
  urd/locales/ja/urd-com.json
  urd/locales/ja/urd-obj.html
  urd/locales/ja/urd-obj.json
  urd/urd-com.html
  urd/urd-com.js
  urd/urd-obj.html
  urd/urd-obj.js
Labels: enhancement

#46 :bug: fix cooperation of urd-obj and EnOcean-Com
  EnOcean/EnOcean-com.js
  EnOcean/EnOcean-obj.html
  EnOcean/EnOcean-obj.js
  EnOcean/config_enocean.json
  EnOcean/locales/en-US/EnOcean-obj.json
  EnOcean/locales/en-US/sensor-core-staff-temperature-humidity-node.json
  EnOcean/locales/en-US/sensor-itec-ct-node.json
  EnOcean/locales/en-US/sensor-optex-occupancy-node.json
  EnOcean/locales/en-US/sensor-optex-rocker-switch-node.json
  EnOcean/locales/en-US/sensor-watty-temperature-node.json
  EnOcean/locales/ja/EnOcean-obj.json
  EnOcean/locales/ja/sensor-core-staff-temperature-humidity-node.json
  EnOcean/locales/ja/sensor-itec-ct-node.json
  EnOcean/locales/ja/sensor-optex-occupancy-node.json
  EnOcean/locales/ja/sensor-optex-rocker-switch-node.json
  EnOcean/locales/ja/sensor-watty-temperature-node.json
  EnOcean/sensor-core-staff-temperature-humidity-node.html
  EnOcean/sensor-core-staff-temperature-humidity.js
  EnOcean/sensor-itec-ct-node.html
  EnOcean/sensor-itec-ct.js
  EnOcean/sensor-optex-occupancy-node.html
  EnOcean/sensor-optex-occupancy.js
  EnOcean/sensor-optex-rocker-switch-node.html
  EnOcean/sensor-optex-rocker-switch.js
  EnOcean/sensor-watty-temperature-node.html
  EnOcean/sensor-watty-temperature.js
  urd/urd-obj.js
Labels: bug, enhancement

#48 Update package.json
  package.json
Labels: bug

#49 Remove file config mode.
  EnOcean/EnOcean-obj.html
  EnOcean/EnOcean-obj.js
  EnOcean/locales/en-US/EnOcean-obj.json
  EnOcean/locales/ja/EnOcean-obj.json
Labels: enhancement

#50 Fix label name.
  urd/urd-ac-3ch-node.html
Labels: bug

#51 Apply editableList for urd-ac-*ch-node.
  urd/locales/en-US/urd-ac-3ch-node.json
  urd/locales/ja/urd-ac-3ch-node.json
  urd/urd-ac-1ch-node.html
  urd/urd-ac-1ch.js
  urd/urd-ac-3ch-node.html
  urd/urd-ac-3ch.js
  urd/urd-obj.js
Labels: enhancement

#52 Update script content-type text/x-red to text/html.
  Caliper-Mitsutoyo/locales/en-US/caliper-Mitsutoyo.html
  EnOcean/EnOcean-obj.html
  EnOcean/sensor-core-staff-temperature-humidity-node.html
  EnOcean/sensor-itec-ct-node.html
  EnOcean/sensor-optex-occupancy-node.html
  EnOcean/sensor-optex-rocker-switch-node.html
  EnOcean/sensor-watty-temperature-node.html
  HMI-Schneider/locales/en-US/HMI-Schneider-com.html
  HMI-Schneider/locales/ja/HMI-Schneider-com.html
  PLC-Nodes/locales/en-US/Modbus-com.html
  PLC-Nodes/locales/en-US/PLC-modbus-AE.html
  PLC-Nodes/locales/en-US/PLC-modbus.html
  ia-cloud-change/ia-cloud-change.html
  ia-cloud-cnct/locales/ja/ia-cloud-cnct.html
  ia-cloud-nfcpy-id/ia-cloud-nfcpy-id.html
  ia-cloud-serialport/ia-cloud-serialport.html
  ibress-cnct/ibress-cloud.html
  ibress-cnct/locales/ja/ibress-cloud.html
  plc-mc-protocol/plc-mc-protocol-config.html
  tmp-ctrl-omron/locales/en-US/omron-temp-ctlr.html
  urd/locales/ja/urd-ac-1ch-node.html
  urd/locales/ja/urd-ac-3ch-node.html
  urd/locales/ja/urd-obj.html
Labels: hacktoberfest-accepted

#53 Fix JavaScript coding style problems/warnings.
  EnOcean/EnOcean-obj.js
  EnOcean/sensor-core-staff-temperature-humidity-node.html
  EnOcean/sensor-core-staff-temperature-humidity.js
  EnOcean/sensor-itec-ct-node.html
  EnOcean/sensor-itec-ct.js
  EnOcean/sensor-optex-occupancy-node.html
  EnOcean/sensor-optex-occupancy.js
  EnOcean/sensor-optex-rocker-switch-node.html
  EnOcean/sensor-optex-rocker-switch.js
  EnOcean/sensor-watty-temperature-node.html
  EnOcean/sensor-watty-temperature.js
Labels: bug

#54 Fix renaming configObject.
  urd/urd-obj.js
Labels: bug

#56 Apply editableList for EnOcean nodes.
  EnOcean/EnOcean-obj.js
  EnOcean/locales/en-US/sensor-core-staff-temperature-humidity-node.json
  EnOcean/locales/en-US/sensor-itec-ct-node.json
  EnOcean/locales/en-US/sensor-optex-occupancy-node.json
  EnOcean/locales/en-US/sensor-optex-rocker-switch-node.json
  EnOcean/locales/en-US/sensor-watty-temperature-node.json
  EnOcean/locales/ja/sensor-core-staff-temperature-humidity-node.json
  EnOcean/locales/ja/sensor-itec-ct-node.json
  EnOcean/locales/ja/sensor-optex-occupancy-node.json
  EnOcean/locales/ja/sensor-optex-rocker-switch-node.json
  EnOcean/locales/ja/sensor-watty-temperature-node.json
  EnOcean/sensor-core-staff-temperature-humidity-node.html
  EnOcean/sensor-core-staff-temperature-humidity.js
  EnOcean/sensor-itec-ct-node.html
  EnOcean/sensor-itec-ct.js
  EnOcean/sensor-optex-occupancy-node.html
  EnOcean/sensor-optex-rocker-switch-node.html
  EnOcean/sensor-optex-rocker-switch.js
  EnOcean/sensor-watty-temperature-node.html
  EnOcean/sensor-watty-temperature.js
Labels: enhancement
